env:
  global:
    - CC_TEST_REPORTER_ID=476a106a4ae7983a49ce2cff5df6aa11aff1b54b3858e494d7778056e676049a
language: node_js
node_js:
  - "8"
install:
  - npm install
  - npm install -g codecov
script:
  - npm run test -- --coverage && codecov
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
deploy:
  provider: heroku
  on: master